# Generated by Django 2.2.6 on 2020-02-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20200209_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_method',
            field=models.TextField(default='Podaj przepis'),
            preserve_default=False,
        ),
    ]
